spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    # url: jdbc:h2:mem:boatvotetestdb
    url: ${DB_URL}
    username: ${DB_ID}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  logging:
    level:
      org.hibernate.SQL: DEBUG

openai:
  api:
    key: ${GPT_API_KEY}