apiVersion: apps/v1
kind: Deployment
metadata:
  name: boatvote-dep
spec:
  selector:
    matchLabels:
      app: boatvote-kube
  replicas: 3
  template:
    metadata:
      labels:
        app: boatvote-kube
    spec:
      containers:
        - name: boatvote-server-container
          image: boatvote-server:0.1
          ports:
            - containerPort: 80
