apiVersion: v1
kind: Service
metadata:
  name: boatvote-service
  namespace: default
spec:
  selector:
    app: boatvote-kube
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080